### ISSUE TITLE
cutekeayboard are not work with InputFields in Dialog or Popup

### ISSUE THREAD

**Issue by freaksdd** [amarula/cutekeyboard#22]
When you have a Dialog or Popup with a Inputfield an focus them, the keyboard will be open in the background.
The reason i have found in the patch of QtVirtualKeyboard. The Dialog and Popup seams to be exec() instead of show(), that blocks all other work.
The Patch make the current inputField to the parent of the InputPanel. So the InputPanel is always enabled. I have tried by my self and it solve the issue.

[https://codereview.qt-project.org/c/qt/qtvirtualkeyboard/+/292472/10](url)

**Comment by AndreaRicchi** [comment]
Closed with #23
